### ISSUE TITLE
Error: cannot estimate gas

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#792]
I saw this error when attempting to swap from the modal after approving the Curve contract for the first time. For some reason, I can't find a corresponding error in Sentry.

[ousd.com-1635136024489.log](https://github.com/OriginProtocol/origin-dollar/files/7407210/ousd.com-1635136024489.log)

**Comment by sparrowDom** [comment]
Fixes the issue: https://github.com/OriginProtocol/origin-dollar/pull/810

**Comment by micahalcorn** [comment]
A user is reporting this error when attempting to swap OUSD for either USDT or USDC via the Flipper.

![revert](https://user-images.githubusercontent.com/273937/178628525-0dc69e66-4a21-4edc-ab46-bdadc95ecdf1.png)

**Comment by franckc** [comment]
I think @micahalcorn has a Nano X

**Comment by sparrowDom** [comment]
@micahalcorn have you ever tried swapping using the NanoX? From console log I assume the user had ledger connected via Metamsk

**Comment by sparrowDom** [comment]
So the problem was that Dapp wasn't detecting that Flipper doesn't have enough funds to perform the swap. User was trying to swap 10k OUSD using flipper. flipper didn't have 10k USDC. Dapp should say "amount too high", but didn't rule Flipper out and was trying to perform the swap.

**Comment by micahalcorn** [comment]
> So the problem was that Dapp wasn't detecting that Flipper doesn't have enough funds to perform the swap. User was trying to swap 10k OUSD using flipper. flipper didn't have 10k USDC. Dapp should say "amount too high", but didn't rule Flipper out and was trying to perform the swap.

Interesting, was that unique to the Ledger? I tried checking that with regular MetaMask connection and Flipper did not show up as an option with larger amounts.

**Comment by sparrowDom** [comment]
Another use has been experiencing this issue this time Firefox/Metamask. So it looks like it is not a Ledger specific issue. 
<img width="1164" alt="Screenshot 2022-08-08 at 09 09 53" src="https://user-images.githubusercontent.com/579910/183360155-5079dc54-1064-485f-8ff4-f95c7be353bb.png">

**Comment by rolandpo** [comment]
done in #1063

**Comment by micahalcorn** [comment]
There's some concern that #1063 doesn't completely resolve this, but none of us have been able to reproduce the issue lately. We'll reopen this with more details if we find anything.
